apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: users-external-secret
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: users-secrets
    creationPolicy: Owner
  data:
    - secretKey: MYSQL_HOST
      remoteRef:
        key: users-db-secret
        property: db_host
    - secretKey: MYSQL_USER
      remoteRef:
        key: users-db-secret
        property: username
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: users-db-secret
        property: password
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: users-db-secret
        property: db_name
