apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-users-api
  labels:
    app: hackathon-users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-users-api
  template:
    metadata:
      labels:
        app: hackathon-users-api
    spec:
      containers:
        - name: users-api
          image: limalucas99/hackathon-users
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: MYSQL_HOST
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: MYSQL_HOST
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: MYSQL_DATABASE
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: MYSQL_USER
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: MYSQL_PASSWORD
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: SHARED_SECRET
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
