apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-users-api
  labels:
    app: hackathon-users-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-users-api
  template:
    metadata:
      labels:
        app: hackathon-users-api
    spec:
      containers:
        - name: users-api
          image: limalucas99/hackathon-users
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: Database__Host
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: DB_HOST
            - name: Database__Name
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: DB_NAME
            - name: Database__User
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: DB_USER
            - name: Database__Password
              valueFrom:
                secretKeyRef:
                  name: users-secrets
                  key: DB_PASSWORD
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
