name: CD
on:
  workflow_dispatch:
jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v4.1.5

      - name: Configurar credenciais AWS (Access Key + Secret + Session Token)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3

      - name: Atualiza kubeconfig
        run: aws eks update-kubeconfig --region us-east-1 --name hackathon-k8s-cluster

      - name: Aplicar manifestos
        run: kubectl apply -f ./k8s
